version: '3.5'


services:

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - ./spark-apps:/opt/workspace/spark-apps
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks
    environment:
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  api_az_function:
    image: api_az_function
    ports:
      - 7071:80
    environment:
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
  
  spark-master:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace
      - ./spark-apps:/opt/workspace/spark-apps
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
  spark-worker-a:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
    volumes:
      - shared-workspace:/opt/workspace
      - ./spark-apps:/opt/workspace/spark-apps
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks
  spark-worker-b:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
    volumes:
      - shared-workspace:/opt/workspace
      - ./spark-apps:/opt/workspace/spark-apps
      - ./data:/opt/workspace/data
      - ./notebooks:/opt/workspace/notebooks

  db:
    container_name: postgres_database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8181

volumes:
  postgres-db:
    driver: local
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  